### ISSUE TITLE
MIME type text/plain used when returning JSON errors

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/GRNOC-WebService#10]
The MIME type at https://github.com/GlobalNOC/GRNOC-WebService/blob/master/lib/GRNOC/WebService/Dispatcher.pm#L125 should be changed from `text/plain` to `application/json`.

**Comment by daldoyle** [comment]
Fixed in https://github.com/GlobalNOC/GRNOC-WebService/commit/4c05054e14fb63e32885a810cca678a92ddae23b
