### ISSUE TITLE
SCTASK0067969 Responses using the provided $method->set_error have a content type of text/plain

### ISSUE THREAD

**Issue by jonstout** [GlobalNOC/GRNOC-WebService#20]
Error payloads are json payloads and should have a content-type of `application/json`. This causes our Python web service client to throw an exception, and I don't believe it's recoverable.

**Comment by khood5** [comment]
fix by merge d7aa91e06634ceaf6c3b45338df2077ad4001b03 
branch "SCTASK0067969_change_response_type_of_Method_pm_to_application_json" into "master"

**Comment by jonstout** [comment]
fixed in #21
